#port
server:
  port: 8888

#database
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie
      username: root
      password: 123456
  #swagger_NullPointerException
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#mybatis
mybatis-plus:
  global-config:
    db-config:
      #\u6309\u7167mybatis-plus\u7684\u96EA\u82B1\u7B97\u6CD5\u751F\u6210\u552F\u4E00id
      id-type: assign_id
  configuration:
    #\u6253\u5370\u5230\u63A7\u5236\u53F0
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

reggie:
  path: F:\image\

#log4j
#logging:
#  config: classpath:logback.xml
#  level:
#    com.hnn: trace
